server:
  port: 9999
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  easy:
    ocr:
      # 百度云配置 去百度云申请自己的账户获取app-id和api-key和secret-key
      baidu:
        app-id: 16782092
        api-key: GuCsGkBxlgHEeup3hVDaL2fj
        secret-key: HhkNVBQD9iR6gtjnrSBsajpbVjjKW7Q3
        open: false
      # 腾讯云配置 去百度云申请自己的账户获取app-id和api-key和secret-key
      qq:
         app-id: 1259630960
         secret-key: AKIDqVv5z5kixxHpQofwd4GDzZviRu8AnXrv
         secret-id: 5vVptiKjszsVzKVK1ZtukLrBF8mCQO6f
         bucket-name:
         open: false